apiVersion: v1
kind: Service
metadata:
  name: mywebsite
spec:
  type: LoadBalancer
  selector:
    app: mywebsite
  ports:
  - protocol: TCP
    port: 80          # External port
    targetPort: 3000  # Port your app is running on inside the container